# Generated by Django 3.2.25 on 2024-09-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50, verbose_name='password')),
            ],
        ),
    ]
